version: '2.2'
services:
  app:
    image: ruby:2.6.1-alpine3.8
    init: true
    command:
      - ruby
      - -run
      - -e
      - httpd
      - index.html
      - -p
      - '5000'
    volumes:
      - ./index.html:/index.html

  test:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - app
    environment:
      FAKETIME_DONT_FAKE_MONOTONIC: 1
      FAKETIME: '2018-12-24 20:30:00'
    volumes:
      - ../spec_helper.rb:/e2e/spec_helper.rb
      - ./fixtures:/e2e/fixtures
      - ./tests:/e2e/spec
